---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "82.15.1"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    crds:
      enabled: true

    prometheus:
      prometheusSpec:
        retention: 14d
        retentionSize: "40GB"
        walCompression: true
        scrapeInterval: 60s
        evaluationInterval: 60s
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 2Gi
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 50Gi
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false

    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 1Gi

    grafana:
      defaultDashboardsEnabled: true
      persistence:
        enabled: false
      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
      envFromSecret: grafana-secret
      grafana.ini:
        server:
          root_url: https://grafana.ringbell.cc
        auth:
          signout_redirect_url: https://auth.ringbell.cc/logout
        auth.generic_oauth:
          enabled: true
          name: Authelia
          icon: signin
          client_id: grafana
          client_secret: $__env{GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
          scopes: openid profile email groups
          auth_url: https://auth.ringbell.cc/api/oidc/authorization
          token_url: https://auth.ringbell.cc/api/oidc/token
          api_url: https://auth.ringbell.cc/api/oidc/userinfo
          login_attribute_path: preferred_username
          name_attribute_path: name
          email_attribute_path: email
          groups_attribute_path: groups
          use_pkce: true
          auto_login: true
          allow_sign_up: true

    nodeExporter:
      enabled: true

    kubeStateMetrics:
      enabled: true

    kubeApiServer:
      enabled: true

    kubeControllerManager:
      enabled: false

    kubeScheduler:
      enabled: false

    kubeEtcd:
      enabled: false
