---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm/onepassword.yaml
  - helm/external-secrets.yaml
  - helm/cilium.yaml
  - helm/jetstack.yaml
  - helm/external-dns.yaml
  - helm/rook-ceph.yaml
  - helm/nfs-subdir.yaml
  - helm/backube.yaml
  - helm/synology-csi-talos.yaml
  - helm/spegel.yaml
  - helm/prometheus-community.yaml
  - helm/authelia.yaml
  - helm/harbor.yaml
  - helm/metrics-server.yaml
  - helm/influxdata.yaml
  - helm/grafana.yaml
  - helm/forgejo.yaml
