---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: synology-csi-talos
  namespace: flux-system
spec:
  url: https://zebernst.github.io/synology-csi-talos
  interval: 24h
