name: nfs-provisioner
namespace: storage
wave: 0
type: helm
adopted: true
repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
chart: nfs-subdir-external-provisioner
version: "4.0.18"
