---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-volsync-restic
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: ${APP}-volsync-restic
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:${GARAGE_S3_ENDPOINT}/${GARAGE_S3_BUCKET}/volsync/${APP}"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .accessKey }}"
        AWS_SECRET_ACCESS_KEY: "{{ .secretKey }}"
  data:
    - secretKey: resticPassword
      remoteRef:
        key: volsync-restic
        property: restic-password
    - secretKey: accessKey
      remoteRef:
        key: volsync-restic
        property: access-key
    - secretKey: secretKey
      remoteRef:
        key: volsync-restic
        property: secret-key
