---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: APP
spec:
  trigger:
    manual: restore-once
  restic:
    repository: APP-volsync-restic
    copyMethod: Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-bulk
    accessModes: ["ReadWriteOnce"]
    capacity: CAPACITY
    cacheStorageClassName: local-nvme
    cacheCapacity: 2Gi
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
