---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-admin
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: forgejo
        property: admin-username
    - secretKey: password
      remoteRef:
        key: forgejo
        property: admin-password
    - secretKey: email
      remoteRef:
        key: forgejo
        property: admin-email
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oauth
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: forgejo-oauth
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: forgejo
        property: oidc-client-id
    - secretKey: secret
      remoteRef:
        key: forgejo
        property: oidc-client-secret
