---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e2e-ceph
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e2e-nfs
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-unraid
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e2e-iscsi
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: synology-iscsi
  resources:
    requests:
      storage: 1Gi
