---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unraid
  namespace: flux-system
spec:
  targetNamespace: networking
  path: ./kubernetes/apps/networking/unraid/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
