---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-secret
    creationPolicy: Owner
  data:
    - secretKey: identity_validation.reset_password.jwt.hmac.key
      remoteRef:
        key: authelia
        property: jwt-secret
    - secretKey: session.encryption.key
      remoteRef:
        key: authelia
        property: session-secret
    - secretKey: storage.encryption.key
      remoteRef:
        key: authelia
        property: storage-encryption-key
    - secretKey: users-yaml
      remoteRef:
        key: authelia
        property: users-yaml
    - secretKey: identity_providers.oidc.hmac.key
      remoteRef:
        key: authelia
        property: oidc-hmac-key
    - secretKey: oidc-jwks-rsa-key
      remoteRef:
        key: authelia
        property: oidc-jwks-private-key
