---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: authelia-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_TOKEN
      remoteRef:
        key: authelia
        property: jwt-secret
    - secretKey: SESSION_ENCRYPTION_KEY
      remoteRef:
        key: authelia
        property: session-secret
    - secretKey: STORAGE_ENCRYPTION_KEY
      remoteRef:
        key: authelia
        property: storage-encryption-key
    - secretKey: users-yaml
      remoteRef:
        key: authelia
        property: users-yaml
