---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    {
      auto_https off
      order forward_auth before reverse_proxy
      servers {
        trusted_proxies static private_ranges
      }
    }

    http://auth-tunnel.ringbell.cc {
      reverse_proxy authelia.auth.svc.cluster.local:80
    }

    http://harbor-tunnel.ringbell.cc {
      reverse_proxy harbor.registry.svc.cluster.local:80
    }

    http://proxmox.ringbell.cc {
      reverse_proxy 192.168.2.194:8006 {
        transport http {
          tls_insecure_skip_verify
        }
      }
    }

    http://nas.ringbell.cc {
      reverse_proxy 192.168.50.177:5001 {
        transport http {
          tls_insecure_skip_verify
        }
      }
    }
