---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: caddy-tunnel
spec:
  endpoints:
    - dnsName: auth-tunnel.ringbell.cc
      recordType: CNAME
      targets:
        - 632934dd-f7ca-456e-92eb-dacfb5043624.cfargotunnel.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
    - dnsName: home-tunnel.ringbell.cc
      recordType: CNAME
      targets:
        - 632934dd-f7ca-456e-92eb-dacfb5043624.cfargotunnel.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
    - dnsName: harbor-tunnel.ringbell.cc
      recordType: CNAME
      targets:
        - 632934dd-f7ca-456e-92eb-dacfb5043624.cfargotunnel.com
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: "true"
