---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: synology-csi
  namespace: flux-system
spec:
  targetNamespace: storage
  path: ./kubernetes/apps/storage/synology-csi/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  prune: true
  wait: true
  dependsOn:
    - name: external-secrets
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
