---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garmin-token-store
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-unraid
  resources:
    requests:
      storage: 1Gi
