---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: client-info-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        client-info.yml: |
          clients:
            - host: {{ .host }}
              port: {{ .port }}
              https: {{ .https }}
              username: {{ .username }}
              password: {{ .password }}
  data:
    - secretKey: host
      remoteRef:
        key: synology-csi
        property: host
    - secretKey: port
      remoteRef:
        key: synology-csi
        property: port
    - secretKey: https
      remoteRef:
        key: synology-csi
        property: https
    - secretKey: username
      remoteRef:
        key: synology-csi
        property: username
    - secretKey: password
      remoteRef:
        key: synology-csi
        property: password
