---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: harbor-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        HARBOR_ADMIN_PASSWORD: "{{ .admin_password }}"
        secretKey: "{{ .secret_key }}"
        CONFIG_OVERWRITE_JSON: |
          {
            "auth_mode": "oidc_auth",
            "oidc_name": "Authelia",
            "oidc_endpoint": "https://auth-tunnel.ringbell.cc",
            "oidc_client_id": "harbor",
            "oidc_client_secret": "{{ .oidc_client_secret }}",
            "oidc_groups_claim": "groups",
            "oidc_admin_group": "",
            "oidc_scope": "openid,profile,email,groups",
            "oidc_verify_cert": true,
            "oidc_auto_onboard": true,
            "oidc_user_claim": "preferred_username"
          }
  data:
    - secretKey: admin_password
      remoteRef:
        key: harbor
        property: admin-password
    - secretKey: secret_key
      remoteRef:
        key: harbor
        property: secret-key
    - secretKey: oidc_client_secret
      remoteRef:
        key: harbor
        property: oidc-client-secret
