---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-os
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cloudflare-os-secret
    creationPolicy: Owner
  data:
    - secretKey: github-client-id
      remoteRef:
        key: cloudflare-os
        property: github-client-id
    - secretKey: github-client-secret
      remoteRef:
        key: cloudflare-os
        property: github-client-secret
